name: cl
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    
jobs:
 my_job:
  name: deploy to staging
  runs-on: ubuntu-latest
  steps: 
  - uses: actions/setup-node@v3
    with:
     node-version: '10.x'
  - name: Setup .NET Core SDK
    uses: actions/setup-dotnet@v3.0.3
  - name: Restore dependencies
    run: dotnet restore
  - name: Build
    run: dotnet build --no-restore
  
